permalink: pretty
title: Astrofluenced & Style Spectrum
description: Exploring human behavior, past, present, future through astrology and design
baseurl: "/astrofluenced"
url: "https://seanivore.github.io" 